### ISSUE TITLE
Missing arm64 Linux images

### ISSUE THREAD

**Issue by frank7y** [networkservicemesh/deployments-k8s#9215]
Hi there,
I noticed that arm64 Linux arch images for many of the NSM images, such as cmd ones, are no longer provided in the latest few versions of NSM. This change has affected, among other things, the possibility to experiment with NSM on Apple Silicon Macs, which is no longer possible. At least not without the hassle of compiling on our own the required images each time. Are there any plans to reintroduce arm64 Linux images in the future?

Thank you for your attention to this matter.

**Comment by denis-tingaikin** [comment]
@frank7y Thanks for poinitng that. Looks critical.

As I found it comes from https://github.com/docker/build-push-action, looks like behaviour by defualt has been changed and some of our release has this defect.

@edwarnicke I think we might need to specify a list of platforms for releasing images.
Probabbly we could simply start with `linux/amd64`
Thoughts?

Also, I think we shoudl re-build all images for all releases that have this defect (should be quicly since we don't need to do changes in code just re-run jobs)

**Comment by denis-tingaikin** [comment]
@NikitaSkrynnik This might be useful for building forwarders https://github.com/edwarnicke/govpp/pull/62

**Comment by edwarnicke** [comment]
> @edwarnicke I think we might need to specify a list of platforms for releasing images.
> Probabbly we could simply start with ` linux/amd64,linux/arm64`
> Thoughts?

That sounds right to me :)

**Comment by denis-tingaikin** [comment]
TODO:

sdk->govpp -> cmd-.*-vpp

-[ ] Include nsm/govpp in release pipeline ~ [3h, 4h]
-[ ] Initial CI~ [7h]
-[ ] Consider version format ~ [7h]
-[ ] IUpdate all nsm apps to use nsm/vovpp  ~ [7h]

TOTAL: 28h

**Comment by edwarnicke** [comment]
> TODO:
> 
> sdk->govpp -> cmd-.*-vpp
> 
> * [ ]  Include nsm/govpp in release pipeline ~ [3h, 4h]
> * [ ]  Initial CI~ [7h]
> * [ ]  Consider version format ~ [7h]
> * [ ]  IUpdate all nsm apps to use nsm/vovpp  ~ [7h]
> 
> TOTAL: 28h

Do we have issues for these other TODOs?  Could we link them here?

**Comment by glazychev-art** [comment]
I think it was closed by mistake

**Comment by denis-tingaikin** [comment]
@edwarnicke Yes, I've created issues in https://github.com/networkservicemesh/govpp/issues

**Comment by denis-tingaikin** [comment]
Seems like done
